# camus.org -*- coding: utf-8; mode: org -*- 

* https://plato.stanford.edu/entries/camus/

* L'été

Mais toi tu es né pour un jour limpide...  (Hölderlin)

| limpide | limpid, clear, transparent; helder |

Cet essai date de 1939.  Le lecteur devra s'en souvenir pour juger de ce que pourrait être l'Oran
d'aujourd'hui.  Des protestations passionnées venues de cette belle ville m'assurent en effet qu'il a
été (ou sera) porté remède à toutes les imperfections.  Les beautés que cet essai exalte, au contraire,
ont été jalousement protégées.  Cité heureuse et réaliste, Oran désormais n'a plus besoin d'écrivains :
elle attend des touristes.  (1953)

** Le minotaure ou la halte d'Oran

Il n'y a plus des déserts.  Il n'y a plus d'îles.  Le besoin pourtant s'en fait sentir.  Pour comprendre
le monde, il faut parfois se détourner ; pour mieux servir les hommes, les tenir un moment à distance.
Mais où trouver la solitude nécessaire à la force, la longue respiration où l'esprit se rassemble et le
courage se mesure ?  Il reste les grandes villes.  Simplement, il y faut encore des conditions.

Les villes que l'Europe nous offre sont trop pleines des rumeurs du passé.  Une oreille exercée peut y
percevoir des bruits d'ailes, une palpitation d'âmes.  On y sent le vertige des siècles, des
révolutions, de la gloire.  On s'y souvient que l'Occident s'est forgé dans les clameurs.  Cela ne fait
pas assez de silence.

Paris est souvent un désert pour le cœur, mais à certaines heures, du haut du Père-Lachaise, souffle un
vent de révolution qui remplit soudain ce désert de drapeaux et de grandeurs vaincues.  Ainsi de
quelques villes espagnoles, de Florence ou de Prague.  Salzbourg serait paisible sans Mozart.  Mais, de
loin en loin, court sur la Salzach le grand cri orgueilleux de don Juan plongeant aux enfers.  Vienne
paraît plus silencieuse, c'est une jeune fille parmi les villes.  Les pierres n'y ont pas plus de trois
siècles et leur jeunesse ignore la mélancolie.  Mais Vienne est à un carrefour d'histoire.  Autour
d'elle retentissent des chocs d'empires.  Certains soirs où le ciel se couvre de sang, les chevaux de
pierre, sur les monuments du Ring, semblent s'envoler.  Dans cet instant fugitif, où tout parle de
puissance et d'histoire, on peut distinctement entendre, sous la ruée des escadrons polonais, la chute
fracassante du royaume ottoman.  Cela non plus fait pas assez de silence.

Certes, c'est bien cette solitude peuplée qu'on vient chercher dans les villes d'Europe.  Du moins, les
hommes qui savent ce qu'ils ont à faire.  Ils peuvent y choisir leur compagnie, la prendre et la
laisser.  Combien d'esprits se sont trempés dans ce voyage entre leur chambre d'hôtel et les vieilles
pierres de l'île Saint-Louis!  Il est vrai que d'autres y ont péri d'isolement.  Pour les premiers, en
tout cas, ils y trouvaient leurs raisons de croître et de s'affirmer.  Ils étaient seuls et ils ne
l'étaient pas.  Des siècles d'histoire et de beauté, le témoignage ardent de mille vies révolues les
accompagnaient le long de la Seine et leur parlaient à la fois de traditions et de conquêtes.  Mais leur
jeunesse les poussait à appeler cette compagnie.  Il vient un temps, des époques, où elle est
importune.  « À nous deux ! » s'écrie Rastignac, devant l'énorme moisissure de la ville parisienne.
Deux, oui, mais c'est encore trop !

Le désert lui-même a pris un sens, on l'a surchargé de poésie.  Pour toutes les douleurs du monde, c'est
un lieu consacré.  Ce que le cœur demande à certains moments, au contraire, ce sont justement des lieux
sans poésie.  Descartes, ayant à méditer, choisit son désert : la ville la plus commerçante de son
époque.  Il y trouve sa solitude et l'occasion du plus grand, peut-être, de nous poèmes virils : « Le
premier (précepte) était de ne recevoir jamais aucune chose pour vraie que je ne la connusse évidemment
être telle. »  On peut avoir moins d'ambition et la même nostalgie.  Mais Amsterdam, depuis trois
siècles, s'est couverte de musées.  Pour fuir la poésie et retrouver la paix des pierres, il faut
d'autres déserts, d'autres lieux sans âme et sans recours.  Oran est l'un de ceux-là.

*** La rue

J'ai souvent entendu des Oranais se plaindre de leur ville : « Il n'y a pas de milieu intéressant. » Eh
! parbleu, vous ne le voudriez pas ; quelques bons esprits ont essayé d'acclimater dans ce désert les
mœurs d'un autre monde, fidèles à ce principe qu'on ne saurait bien servir, l'art ou les idées sans se
mettre à plusieurs *.

 * On rencontre à Oran le Klestakoff de Gogol.  Il bâille et puis : « Je sens qu'il va falloir s'occuper
de quelque chose d'élevé. »

Le résultat est tel que les seuls milieux instructifs restent ceux des joueurs de poker, des amateurs de
boxe, des boulomanes et des sociétés régionales.  Là, du moins, règne le naturel.  Après tout, il existe
une certaine grandeur qui ne prête pas à l'élévation.  Elle est inféconde par état.  Et ceux qui
désirent la trouver, ils laissent les « milieux » pour descendre dans la rue.

Les rues d'Oran sont vouées à la poussière, aux cailloux et à la chaleur.  S'il y pleut, c'est le déluge
et une mer de boue.  Mais pluie ou soleil, les boutiques ont le même air extravagant et absurde.  Tout
le mauvais goût de l'Europe et de l'Orient s'y est donné rendez-vous.  On y trouve, pêle-mêle, des
lévriers de marbre, des danseuses au cygne, des Dianes chasseresses en galalithe verte, des lanceurs de
disque et des moissonneurs, tout ce qui sert aux cadeaux d'anniversaire ou de mariage, tout le peuple
affligeant qu'un génie commercial et farceur ne cesse de susciter sur les dessus de nos cheminées.  Mais
cette application dans le mauvais goût  prend ici une allure baroque qui fait tout pardonner.  Voici,
offert dans un écrin de poussière, le contenu d'une vitrine : d'affreux modèles en plâtre de pieds
torturés, un lot de dessins de Rembrandt « sacrifiés à 150 francs l'un », des « farces-attrapes », des
porte-billets tricolores, un pastel du XVIIIe siècle, un bourricot mécanique en peluche, des bouteilles
d'eau de Provence pour conserver les olives vertes, et une ignoble vierge en bois, au sourire indécent.
(Pour que nul n'en ignore, la « direction » a placé à ses pieds un écriteau : « Vierge en bois. »)

| voué              | reserved for; gewijd            |
| caillou, cailloux | m., kiezel, grind               |
| boue              | f., bagger, modder              |
| pluie             | f., regen                       |
| soleil            | m., zon                         |
| boutique          | f., boetiek, shop, winkel       |
| pêle-mêle         | dooreen, door elkaar            |
| lévrier           | m., windhond                    |
| moissonneur       | m., harvesters; maaier, oogster |
| affligeant        | bedroeven; depressing           |

On peut trouver à Oran:

1. Des cafés au comptoir verni de crasse, saupoudré de pattes et d'ailes de mouches, le patron toujours
souriant, malgré la salle toujours déserte.  Le « petit noir » y coûtait douze sous et le grand,
dix-huit.

| verni de  | gevernist met                   |
| crasse    | f., vet, smerigheid, viezigheid |
| saupoudré | besprenkeld, bestrooid          |
| pattes    | f., poten                       |
| aile      | f., vleugel                     |

2. Des boutiques de photographes où la technique n'a pas progressé depuis l'invention du papier
sensible.  Elles exposent une faune singulière, impossible à rencontrer dans les rues, depuis le
pseudo-marin qui s'appuie du coude sur une console, jusqu'à la jeune fille à marier, taille fagotée,
bras ballants devant un fond sylvestre.  On peut supposer qu'il ne s'agit pas de portraits d'après
nature : ce sont des créations.

| singulière | bijzonder                 |

3. Une édifiante abondance de magasins funéraires.  Ce n'est pas qu'à Oran on meure plus qu'ailleurs,
mais j'imagine seulement qu'on en fait plus d'histoires.

| édifiante              | instructieve, leerrijke; stichtelijke |
| faire plus d'histoires | make more fuss about it               |

La sympathique naïveté de ce peuple marchand s'étale jusque dans la publicité.  Je lis, sur le
prospectus d'un cinéma oranais, l'annonce d'un film de troisième qualité.  J'y relève les adjectifs «
fastueux », « splendide », « extraordinaire », « prestigieux », « bouleversant » et « formidable ».
Pour finir, la direction informe le public des sacrifices considérables qu'elle s'est imposés, afin de
pouvoir lui présenter cette étonnante « réalisation ».  Cependant, le prix des places ne sera pas
augmenté.

On aurait tort de croire que s'exerce seulement ici le goût de l'exagération propre au Midi.
Exactement, les auteurs de ce merveilleux prospectus donnent la preuve de leur sens psychologique.  Il
s'agit (le vaincre l'indifférence et l'apathie profonde qu'on ressent dans ce pays dés qu'il s'agit de
choisir entre deux spectacles, deux métiers et, souvent même, deux femmes.  On ne se décide que forcé.
Et la publicité le sait bien.  Elle prendra des proportions américaines, ayant les mêmes raisons, ici et
là-bas, de s'exaspérer.

Les rues d'Oran nous renseignent enfin sur les deux plaisirs essentiels de la jeunesse locale : se faire
cirer les souliers et promener ces mêmes souliers sur le boulevard.  Pour avoir une idée juste de la
première de ces voluptés, il faut confier ses chaussures, à dix heures, un dimanche matin, aux cireurs
du boulevard Gallieni.  Juché sur de hauts fauteuils, on pourra goûter alors cette satisfaction
particulière que donne, même à un profane, le spectacle d'hommes amoureux de leur métier comme le sont
visiblement les cireurs oranais.  Tout est travaillé dans le détail.  Plusieurs brosses, trois variétés
de chiffons, le cirage combiné à l'essence : on peut croire que l'opération est terminée devant le
parfait éclat qui naît sous la brosse douce.  Mais la même main acharnée repasse du cirage sur la
surface brillante, la frotte, la ternit, conduit la crème jusqu'au cœur des peaux et fait alors jaillir,
sous la même brosse, un double et vraiment définitif éclat sorti des profondeurs du cuir.

Les merveilles ainsi obtenues sont ensuite exhibées devant les connaisseurs.  Il convient, pour
apprécier ces plaisirs tirés du boulevard, d'assister aux bals masqués de la jeunesse qui ont lieu tous
les soirs sur les grandes artères de la ville.  Entre seize et vingt ans, en effet, les jeunes Oranais
de la « Société » empruntent leurs modèles d'élégance au cinéma américain et se travestissent avant
d'aller dîner.  Chevelure ondulée et gominée, débordant d'un feutre penché sur l'oreille gauche et cassé
sur l'œil droit, le cou serré dans un col assez considérable pour prendre le relais des cheveux, le nœud
de cravate microscopique soutenu par une épingle rigoureuse, le veston à mi-cuisse et la taille tout
près des hanches, le pantalon clair et court, les souliers éclatants sur leur triple semelle, cette
jeunesse, tous les soirs, fait sonner sur les trottoirs son imperturbable aplomb et le bout ferré de
ses chaussures.  Elle s'applique en toutes choses à imiter l'allure, la rondeur et la supériorité de
M. Clark Gable.  À ce titre, les esprits critiques de la ville surnomment communément ces jeunes gens,
par la grâce d'une insouciante prononciation, les « Clarque ».

Dans tous les cas, les grands boulevards d'Oran sont envahis, à la fin des après-midi, par une armée de
sympathiques adolescents qui se donnent le plus grand mal pour paraître de mauvais garçons.  Comme les
jeunes Oranaises se sentent promises de tout temps à ces gangsters au cœur tendre, elles affichent
également le maquillage et l'élégance des grandes actrices américaines.  Les mêmes mauvais esprits les
appellent en conséquence des « Marlène ».  Ainsi, lorsque sur les boulevards du soir un bruit d'oiseaux
monte des palmiers vers le ciel, des dizaines de Clarque et de Marlène se rencontrent, se toisent et
s'évaluent, heureux de vivre et de paraître, livrés pour une heure au vertige des existences parfaites.
On assiste alors, disent les jaloux, aux réunions de la commission américaine.  Mais on sent à ces mots
l'amertume des plus de trente ans qui n'ont rien à faire dans ces jeux.  Ils méconnaissent ces congrès
quotidiens de la jeunesse et du romanesque.  Ce sont, en vérité, les parlements d'oiseaux qu'on
rencontre dans la littérature hindoue.  Mais on n'agite pas sur les boulevards d'Oran le problème de
l'être et l'on ne s'inquiète pas du chemin de la perfection.  Il ne reste que des battements d'ailes,
des roues empanachées, des grâces coquettes et victorieuses, tout l'éclat d'un chant insouciant qui
disparaît avec la nuit.

J'entends d'ici Klestakoff : « Il faudra s'occuper de quelque chose d'élevé. »  Hélas ! il en est bien
capable.  Qu'on le pousse et il peuplera ce désert avant quelques années.  Mais, pour le moment, une âme
un peu secrète doit se délivrer dans cette ville facile, avec son défilé de jeunes filles fardées, et
cependant incapable d'apprêter l'émotion, simulant si mal la coquetterie que la ruse est tout de suite
éventée.  S'occuper de quelque chose d'élevé !  Voyez plutôt : Santa Cruz ciselée dans le roc, les
montagnes, la mer plate, le vent violent et le soleil, les grandes grues du port, les trains, les
hangars, les quais et les rampes gigantesques qui gravissent le rocher de la ville, et dans la ville
elle-même ces jeux et cet ennui, ce tumulte et cette solitude.  Peut-être, en effet, tout cela n'est-il
pas assez élevé.  Mais le grand prix de ces îles surpeuplées, c'est que le cœur s'y dénude.  Le silence
n'est plus possible que dans les villes bruyantes.  D'Amsterdam, Descartes écrit au vieux Balzac : « Je
vais me promener tous les jours parmi la confusion d'un grand peuple, avec autant de liberté et de repos
que vous sauriez faire dans vos allées. »

*** Le désert à Oran

Forcés de vivre devant un admirable paysage, les Oranais ont triomphé de cette redoutable épreuve en se
couvrant de constructions bien laides.  On s'attend à une ville ouverte sur la mer, lavée, rafraîchie
par la brise des soirs.  Et, mis à part le quartier espagnol, on trouve une cité qui présente le dos à
la mer, qui s'est construite en tournant sur elle-même, à la façon d'un escargot.  Oran est un grand mur
circulaire et jaune, recouvert d'un ciel dur.  Au début, on erre dans le labyrinthe, on cherche la mer
comme le signe d'Ariane.  Mais on tourne en rond dans les rues fauves et oppressantes, et, à la fin, le
Minotaure dévore les Oranais : c'est l'ennui.  Depuis longtemps, les Oranais n'errent plus.  Ils ont
accepté d'être mangés.

On ne peut pas savoir ce qu'est la pierre sans venir à Oran.  Dans cette ville poussiéreuse entre
toutes, le caillou est roi.  On l'aime tant que les commerçants l'exposent dans leurs vitrines pour
maintenir des papiers, ou encore pour la seule montre.  On en fait des tas le long des rues, sans doute
pour le plaisir des yeux, puisque, un an après, le tas est toujours là.  Ce qui, ailleurs, tire sa
poésie du végétal, prend ici un visage de pierre.  On a soigneusement recouvert de poussière la centaine
d'arbres qu'on peut rencontrer dans la ville commerçante.  Ce sont des végétaux pétrifiés qui laissent
tomber de leurs branches une odeur âcre et poussiéreuse.  À Oran, au-dessus du ravin Ras-el-Aïn, face à
la mer cette fois, ce sont, plaqués contre le ciel bleu, des champs de cailloux crayeux et friables où
le soleil allume d'aveuglants incendies.  Au milieu de ces ossements de la terre, un géranium pourpre,
de loin en loin, donne sa vie et son sang frais au paysage.  La ville entière s'est figée dans une
gangue pierreuse.  Vue des Planteurs, l'épaisseur des falaises qui l'enserrent est telle que le paysage
devient irréel à force d'être minéral.  L'homme en est proscrit.  Tant de beauté pesante semble venir
d'un autre monde.

Si l'on peut définir le désert un lieu sans âme où le ciel est seul roi, alors Oran attend ses
prophètes.  Tout autour et au-dessus de la ville, la nature brutale de l'Afrique est en effet parée de
ses brûlants prestiges.  Elle fait éclater le décor malencontreux dont on la couvre, elle pousse ses
cris violents entre chaque maison et au-dessus de tus les toits.  Si l'on monte sur une des routes, au
flanc de la montagne de Santa-Cruz, ce qui apparaît d'abord, ce sont les cubes dispersés et coloriés
d'Oran.  Mais un peu plus haut, et déjà les falaises déchiquetées qui entourent le plateau
s'accroupissent dans la mer comme des bêtes rouges.  Un peu plus haut encore, et des grands tourbillons
de soleil et de vent recouvrent, aèrent et confondent la ville débraillée, dispersée sans ordre aux
quatre coins d'un paysage rocheux.  Ce qui s'oppose ici, c'est la magnifique anarchie humaine et la
permanence d'une mer toujours égale.  Cela suffit pour que monte vers la route à flanc de coteau une
bouleversante odeur de vie.

Le désert a quelque chose d'implacable.  Le ciel minéral d'Oran, ses rues et ses arbres dans leur enduit
de poussière, tout contribue à créer cet univers épais et impassible où le cœur et l'esprit ne sont
jamais distraits d'eux-mêmes, ni de leur seul objet qui est l'homme.  Je parle ici de retraites
difficiles.  On écrit des livres sur Florence ou Athènes.  Ces villes ont formé tant d'esprits européens
qu'il faut bien qu'elles aient un sens.  Elles gardent de quoi attendrir ou exalter.  Elles apaisent une
certaine faim de l'âme dont l'aliment est le souvenir.  Mais comment s'attendrir sur une ville où rien
ne sollicite l'esprit, où la laideur même est anonyme, où le passé est réduit à rien ? Le vide, l'ennui,
un ciel indifférent, quelles sont les séductions de ces lieux ? C'est sans doute la solitude et,
peut-être, la créature.  Pour une certaine race d'hommes, la créature, partout où elle est belle, est
une amère patrie.  Oran est l'une de ses mille capitales.

*** Les jeux

Le Central Sporting Club, rue du Fondouk, à Oran, donne une soirée pugilistique dont il affirme qu'elle
sera appréciée par les vrais amateurs.  En style clair, cela signifie que les boxeurs à l'affiche sont
loin d'être des vedettes, que quelques-uns d'entre eux montent sur le ring pour la première fois, et
qu'en conséquence on peut compter, sinon sur la science, du moins sur le cœur des adversaires.  Un
Oranais m'ayant électrisé par la promesse formelle « qu'il y aurait du sang », je me trouve ce soir-là
parmi les vrais amateurs.

Apparemment, ceux-ci ne réclament jamais de confort.  On a, en effet, dressé un ring au fond d'une sorte
de garage crépi à la chaux, couvert de tôle ondulée et violemment éclairé.  Des chaises pliantes ont été
rangées en carré autour des cordes.  Ce sont les « rings d'honneur ».  On a disposé des sièges dans la
longueur, et, au fond de la salle, s'ouvre un vaste espace libre nommé promenoir, en raison du fait que
pas une des cinq cents personnes qui s'y trouvent ne saurait tirer son mouchoir sans provoquer de graves
accidents.  Dans cette caisse rectangulaire respirent un millier d'hommes et deux ou trois femmes — de
celles qui, selon mon voisin, tiennent toujours « à se faire remarquer ».  Tout le monde sue
férocement.  En attendant les combats d'« espoirs », un gigantesque pick-up broie du Tino Rossi.  C'est
la romance avant le meurtre.

La patience d'un véritable amateur est sans limites.  La réunion annoncée pour vingt et une heures n'est
pas encore commencée à vingt et une heure trente, et personne n'a protesté.  Le printemps est chaud,
l'odeur d'une humanité en manches de chemise exaltante.  On discute ferme parmi les éclatements
périodiques des bouclions de limonade et l'inlassable lamentation du chanteur corse.  Quelques nouveaux
arrivants sont encastrés dans le publie, quand un projecteur fait pleuvoir une lumière aveuglante sur le
ring.  Les combats d'espoirs commencent.

Les espoirs, ou débutants, qui combattent pour le plaisir, ont toujours à cœur de le prouver en se
massacrant d'urgence, au mépris de toute technique.  Ils n'ont jamais pu durer plus de trois rounds.  Le
héros de la soirée à cet égard est le jeune « Kid Avion » qui, pour l'ordinaire, vend des billets de
loterie aux terrasses des cafés.  Son adversaire, en effet, a capoté malencontreusement hors du ring, au
début du deuxième round, sous le choc d'un poing manié comme une hélice.

La foule s'est un peu animée, mais c'est encore une politesse.  Elle respire avec gravité l'odeur sacrée
de l'embrocation.  Elle contemple ces successions de rites lents et de sacrifices désordonnés, rendus
plus authentiques encore par les dessins propitiatoires, sur la blancheur du mur, des ombres
combattantes.  Ce sont les prologues cérémonieux d'une religion sauvage et calculée.  La transe ne
viendra que plus tard.

Et, justement, le pick-up annonce Amar, « le coriace Oranais qui n'a pas désarmé », contre Pérez, « le
puncheur algérois ».  Un profane interpréterait mal les hurlements qui accueillent la présentation des
boxeurs sur le ring.  Il imaginerait quelque combat sensationnel où les boxeurs auraient à vider une
querelle personnelle, connue du publie.  Au vrai, c'est bien une querelle qu'ils vont vider.  Mail il
s'agit de celle qui, depuis cent ans, divise mortellement Alger et Oran.  Avec un peu de recul dans les
siècles, ces deux villes nord-africaines ne seraient déjà saignées à blanc, comme le firent Pise et
Florence en des temps plus heureux.  Leur rivalité est d'autant plus forte qu'elle ne tient sans doute à
rien.  Ayant toutes les raisons de s'aimer, elles détestent en proportion.  Les Oranais accusent les
Algérois de « chiqué ».  Les Algérois laissent entendre que les Oranais n'ont pas l'usage du monde.  Ce
sont là des injures plus sanglantes qu'il n'apparaît, parce qu'elles sont métaphysiques.  Et faute de
pouvoir s'assiéger, Oran et Alger se rejoignent, luttent et s'injurient sur le terrain du sport, des
statistiques et des grands travaux.

C'est donc une page d'histoire qui se déroule sur le ring.  Et le coriace Oranais, soutenu par un
millier de voix hurlantes, défend contre Pérez une manière de vivre et l'orgueil d'une province.  La
vérité oblige à dire qu'Amar mène mal sa discussion.  Son plaidoyer a un vice de forme : il manque
d'allonge.  Celui du puncheur algérois, au contraire, a la longueur voulue.  Il porte avec persuasion
sur l'arcade sourcilière de son contradicteur.  L'Oranais pavoise magnifiquement, au milieu des
vociférations d'un public déchaîné.  Malgré les encouragements répétés de la galerie et de mon voisin,
malgré les intrépides « Crève-le », « Donne-lui de l'orge », les insidieux « Coup bas », « Oh !
l'arbitre, il a rien vu », les optimistes « Il est pompé », « Il en peut plus », l'Algérois est proclamé
vainqueur aux points sous d'interminables huées.  Mon voisin, qui parle volontiers d'esprit sportif,
applaudit ostensiblement, dans le temps où il me glisse d'une voix éteinte par tant de cris : « Comme
ça, il ne pourra pas dire là-bas que les Oranais sont des sauvages. »

Mais, dans la salle, des combats que le programme ne comportait pas ont déjà éclaté.  Des chaises sont
brandies, la police se fraye un chemin, l'exaltation est à son comble.  Pour calmer ces bons esprits et
contribuer au retour du silence, la « direction », sans perdre un instant, charge le pick-up de
vociférer Sambre-et-Meuse.  Pendant quelques minutes, la salle a grande allure.  Des grappes confuses de
combattants et d'arbitres bénévoles oscillent sous des poignes d'agents, la galerie exulte et réclame la
suite par le moyen de cris sauvages, de cocoricos ou de miaulements farceurs noyés dans le fleuve
irrésistible de la musique militaire.

Mais il suffit de l'annonce du grand combat pour le calme revienne.  Cela se fait brusquement, sans
fioritures, comme des acteurs quittent le plateau, une fois la pièce finie.  Avec le plus grand naturel,
les chapeaux sont époussetés, les chaises rangées, et tous les visages revêtent sans transition
l'expression bienveillante de spectateur honnête qui a payé sa place pour assister à un concert de
famille.

Le dernier combat oppose un champion français de la marine à un boxeur oranais.  Cette fois, la
différence d'allonge est au profit de ce dernier.  Mais ses avantages, pendant les premiers rounds, ne
remuent pas la foule.  Elle cuve, son excitation, elle se remet.  Son souffle est encore court.  Si elle
applaudit, la passion n'y est pas.  Elle siffle sans animosité.  La salle se partage en deux camps, il
le faut bien pour la bonne règle.  Mais le choix de chacun obéit à cette indifférence qui suit les
grandes fatigues.  Si le Français « tient », si l'Oranais oublie qu'on n'attaque pas avec la tête, le
boxeur est courbé par une bordée de sifflets, mais aussitôt redressé par une salve d'applaudissements.
Il faut arriver au septième round pour que le sport revienne à la surface, dans le même temps où les
vrais amateurs commencent à émerger de leur fatigue.  Le Français, en effet, est allé au tapis et,
désireux de regagner des points, s'est rué sur son adversaire. « Ça y est, a dit mon voisin, ça va être
la corrida. »  En effet, c'est la corrida. Couverts de sueur sous l'éclairage implacable, les deux
boxeurs ouvrent leur garde, tapent en fermant les yeux, poussent les épaules et des genoux, échangent
leur sang et reniflent de fureur.  Du même coup, la salle s'est dressée et scande les efforts de ses
deux héros.  Elle reçoit les coups, les rend, les fait retenir en mille voix sourdes et haletantes.  Les
mêmes qui avaient choisi leur favori dans l'indifférence se tiennent dans leur choix par entêtement, et
s'y passionnent.  Toutes les dix secondes, un cri de mon voisin pénètre dans mon oreille droite : «
Vas-y, col bleu, allez, marine ! » pendant qu'un spectateur devant nous hurle à l'Oranais : « Anda !
hombre ! » L'homme et le col bleu y vont et, avec aux, dans ce temple de chaux, de tôle et de ciment,
une salle tout entière livrée à des dieux au front bas.  Chaque coup qui sonne mat sur les pectoraux
luisants retentit en vibrations énormes dans le corps même de la foule qui fournit avec les boxeurs son
dernier effort.

Dans cette atmosphère, le match nul est mal accueilli.  Il contrarie dans le public, en effet, une
sensibilité toute manichéenne.  Il y a le bien et le mal, le vainqueur et le vaincu.  Il faut avoir
raison si l'on n'a pas tort.  La conclusion de cette logique impeccable est immédiatement fournie par
deux mille poumons énergiques qui accusent les juges d'être vendus, ou achetés.  Mais le col bleu est
allé embrasser son adversaire, immédiatement retournée, éclate en applaudissements.  Mon voisin a
raison : ce ne sont pas des sauvages.

La foule qui s'écoule au-dehors, sous un ciel plein de silence et d'étoiles, vient de livrer le plus
épuisant des combats.  Elle se tait, disparaît furtivement, sans forces pour l'exégèse.  Il y a le bien
et le mal, cette religion est sans merci.  La cohorte des fidèles n'est plus qu'une assemblée d'ombres
noires et blanches qui disparaît dans la nuit.  C'est que la force et la violence sont des dieux
solitaires.  Ils ne donnent rien au souvenir.  Ils distribuent, au contraire, leurs miracles à pleines
poignées dans le présent.  Ils sont à la mesure de ce peuple sans passé qui célèbre ses communions
autour des rings.  Ce sont des rites un peu difficiles, mais qui simplifient tout.  Le bien et le mal,
le vainqueur et le vaincu : à Corinthe, deux temples voisinaient, celui de la Violence et celui de la
Nécessité.

*** Les monuments

Pour bien des raisons qui tiennent autant à l'économie qu'à la métaphysique, on peut dire, que le style
oranais, s'il en est un, s'est illustré avec force et clarté dans le singulier édifice appelé Maison du
Colon.  De monuments, Oran ne manque guère.  La ville a son compte de maréchaux d'Empire, de ministres
et de bienfaiteurs locaux.  On les rencontre sur des petites places poussiéreuses, résignés à la pluie
comme au soleil, convertis eux aussi à la pierre et à l'ennui.  Mais ils représentent cependant des
apports extérieurs.  Dans cette heureuse barbarie, ce sont les marques regrettables de la civilisation.

Oran, au contraire, s'est élevé à elle-même ses autels et ses rostres.  En plein cœur de la ville
commerçante, ayant à construire une maison commune pour les innombrables organismes agricoles qui font
vivre ce pays, les Oranais ont médité d'y bâtir, dans le sable et la chaux, une image convaincante de
leurs vertus : la Maison du Colon.  Si l'on en juge par l'édifice, ces vertus sont au nombre de trois :
la hardiesse dans le goût, l'amour de la violence, et le sens des synthèses historiques.  L'Égypte,
Byzance et Munich ont collaboré à la délicate construction d'une pâtisserie figurant une énorme coupe
renversée.  Des pierres multicolores, du plus vigoureux effet, sont venues encadrer le toit.  La
vivacité de ces mosaïques est si persuasive qu'au premier abord on ne voit rien, qu'un éblouissement
informe.  Mais de plus près, et l'attention éveillée, on voit qu'elles ont un sens : un gracieux colon,
à nœud papillon et à casque de liège blanc, y reçoit l'hommage d'un cortège d'esclaves vêtus à
l'antique.  L'édifice et ses enluminures ont été enfin placés au milieu d'un carrefour, dans le
va-et-vient des petits tramways à nacelle dont la saleté est un des charmes de la ville.

Oran tient beaucoup d'autre part aux deux lions de sa place d'Armes.  Depuis 1888, ils trônent de chaque
côté de l'escalier municipal.  Leur auteur s'appelait Caïn.  Ils ont de la majesté et le torse court.
On raconte que, la nuit, ils descendent l'un après l'autre de leur socle, tournent silencieusement
autour de la place obscure, et, à l'occasion, urinent longuement sous les grands ficus poussiéreux.  Ce
sont, bien entendu, des on-dit auxquels les Oranais prêtent une oreille complaisante.  Mais cela est
invraisemblable.

Malgré quelques recherches, je n'ai pu me passionner pour Caïn.  J'ai seulement appris qu'il avait la
réputation d'un animalier adroit.  Cependant, je pense souvent à lui.  C'est une pente d'esprit qui vous
vient à Oran.  Voici un artiste au nom sonore qui a laissé ici une œuvre sans importance.  Plusieurs
centaines de milliers d'hommes sont familiarisés avec les fauves débonnaires qu'il a placés devant une
mairie prétentieuse.  C'est une façon comme une autre de réussir en art.  Sans doute, ces deux lions,
comme des milliers d'œuvres du même genre, témoignent de tout autre chose que de talent.  On a pu faire
la « Ronde de Nuit », « saint François recevant les stigmates », « David » ou « l'Exaltation de la Fleur
».  Caïn, lui, a dressé deux mufles hilares sur la place d'une province commerçante, outre-mer.  Mais
le David croulera un jour avec Florence et les lions seront peut-être sauvés du désastre.  Encore une
fois, ils témoignent d'autre chose.

Peut-on préciser cette idée ?  Il y a dans cette œuvre de l'insignifiance et de la solidité.  L'esprit
n'y est pour rien et la matière pour beaucoup.  La médiocrité veut durer par tous les moyens, y compris
le bronze.  On lui refuse ses droits à l'éxternité et elle les prend tous les jours.  N'est-ce pas elle,
l'éternité ?  En tout cas, cette persévérance a de quoi émouvoir, et elle porte sa leçon, celle de tous
les monuments d'Oran et d'Oran elle-même.  Une heure par jour, une fois parmi d'autres, elle vous force
à porter attention à ce qui n'a pas d'importance.  L'esprit trouve profit à ces retours.  C'est un peu
son hygiène, et, puisqu'il lui faut absolument ses moments d'humilité, il me semble que cette occasion
de s'abêtir est meilleure que d'autres.  Tout ce qui est périssable désire durer.  Disons donc que tout
veut durer.  Les œvres humaines ne signifient rien d'autre et, à cet égard, les lions de Caïn ont les
mêmes chances que les ruines d'Angkor.  Cela incline à la modestie.

Il est d'autres monuments oranais.  Ou du moins, il faut bien leur donner ce nom puisque eux aussi
témoignent pour leur ville, et de façon plus significative peut-être.  Ce sont les grands travaux qui
recouvrent actuellement la côte sur une dizaine de kilomètres.  En principe, il s'agit de transformer la
plus lumineuse des baies en un port gigantesque.  En fait, c'est encore une occasion pour l'homme de se
confronter avec la pierre.

Dans les tableaux de certains maîtres flamands on voit revenir avec insistance un thème d'une ampleur
admirable : la construction de la Tour de Babel.  Ce sont des paysages démesurés, des roches qui
escaladent le ciel, des escarpements où foisonnent ouvriers, bêtes, échelles, machines étranges, cordes,
traits.  L'homme, d'ailleurs, n'est là que pour faire mesurer la grandeur inhumaine du chantier.  C'est
à cela qu'on pense sur la corniche oranaise, à l'ouest de la ville.

Accrochés à d'immenses pentes, des railes, des wagonnets, des grues, des trains minuscules...   Au
milieu d'un soleil dévorant, des locomotives pareilles à des jouets contournent d'énormes blocs parmi
les sifflets, la poussière et la fumée.  Jour et nuit, un peuple de fourmis s'activent sur la carcasse
fumante de la montagne.  Pendus le long d'une même corde contre le flanc de la falaise, des dizaines
d'hommes, le ventre appuyé aux poignées des défonceuses automatiques, tressaillent dans le vide à
longeur de journée, et détachent des pans entiers de rochers qui croulent dans la poussière et les
grondements.  Plus loin, des wagonnets se reversent au-dessus des pentes, et les rochers, déversés
brusquement vers la mer, s'élancent et roulent dans l'eau, chaque gros bloc suivi d'une volée de pierres
plus légèes.  À intervalles réguliers, dans le cœur de la nuit, en plein jour, des détonations ébranlent
toute la montagne et soulèvent la mer elle-même.

L'homme, au milieu de ce chantier, attaque la pierre de front.  Et si l'on pouvait oublier, un instant
au moins, le dur esclavage qui rend possible ce travail, il faudrait admirer.  Ces pierres, arrachées à
la montagne, servent l'homme dans ses desseins.  Elles s'accumulent sous les premières vagues, émergent
peu à peu et s'ordonnent enfin suivant une jetée, bientôt couverte d'hommes et de machines, qui avancent
jour après jour, vers le large.  Sans désemparer, d'énormes mâchoires d'acier fouillent le ventre de la
falaise, tournent sur elles-mêmes, et viennent dégorger dans l'eau leur trop-plein de pierrailles.  À
mesure que le front de la corniche s'abaisse, la côte entière gagne irrésistiblement sur la mer.

Bien sûr, détruire la pierre n'est pas possible.  On la change seulement de place.  De toute façon, elle
durera plus que les hommes qui s'on servent.  Pour le moment, elle appuie leur volonté d'action.  Cela
même sans doute est inutile.  Mais changer les choses de place, c'est le travail des hommmes : il faut
choisir de faire cela ou rien.  Visiblement, les Oranais ont choisi.  Devant cette baie indifférente,
pendant des années encore, ils entasseront des amas de cailloux le long de la côte.  Dans cent ans,
c'est-à-dire demain, il faudra recommencer.  Mais aujourd'hui ces amoncellements de rochers témoignent
pour les hommes au masque de poussière et de sueur qui circulent au milieu d'eux.  Les vrais monuments
d'Oran, ce sont encore ses pierres.

*** La pierre d'Ariane

Il semble que les Oranais soient comment cet ami de Flaubert qui, au moment de mourir, jetant un dernier
regard sur cette terre irremplaçable, s'écriait : « Fermez la fenêtre, c'est trop beau. »  Ils ont fermé
la fenêtre, ils se sont emmurés, ils ont exorcisé le paysage.  Mais le Poittevin est mort, et, après
lui, les jours ont continué de rejoindre les jours.  De même, au-delà des murs jaunes d'Oran, la mer et
la terre a toujours eu pour l'homme des prestiges opposés.  Elle le désespère et l'exalte.  Le monde ne
dit jamais qu'une seule chose, et il intéresse, puis il lasse.  Mais, à la fin, il l'importe à force
d'obstination.  Il a toujours raison.

Déjà, aux portes mêmes d'Oran, la nature hausse le ton.  Du côté de Canastel, ce sont d'immenses
friches, couvertes de broussailles odorantes.  Le soleil et le vent n'y parlent que de solitude.
Au-dessus d'Oran, c'est la montagne de Santa Cruz, le plateau et les mille ravins qui y mènent.  Des
routes, jadis carrossables, s'accrochent au flanc des coteaux qui dominent la mer.  Au mois de janvier,
certaines sont couvertes de fleurs.  Pâquerettes et boutons d'or en font des allées fastueuses, brodées
de jaune et de blanc.  De Santa Cruz, tout a été dit.  Mais si j'avais à en parler, j'oublierais les
cortèges sacrés qui gravissent la dure colline, aux grandes fêtes, pour évoquer d'autres pèlerinages.
Solitaires, ils cheminent dans la pierre rouge, s'élèvent au-dessus de la baie immobile, et viennent
consacrer au dénuement une heure lumineuse et parfaite.



* Journaux de voyage https://www.theparisreview.org/blog/2023/03/14/camuss-new-york-diary-1946/

                                               ÉTATS-UNIS
                                            Mars à mai 1946

Amérique.  Départ.  La légère angoisse propre à tout départ est passée.  Dans le train, je retrouve R.,
psychiatre qui va là-bas prendre des contacts.  Je sais qu'il sera dans ma cabine sur le bateau et ça ne
m'est pas désagréable parce que je le trouve fin et sympathique.  Dans mon compartiment, trois gosses
assez turbulents au départ, mais qui s'assoupiront, leur petite bonne, leur mère, grand et élégante
femme aux yeux clairs et un petit bout de femme blonde, qui pleure en face de moi.  Voyage sans
histoire, sauf une.  Je rends quelques services à la jeune femme blonde.  Avant Rouen, une sorte de
grande femme vêtue d'une longue fourrure de bête et aux traits épatés m'interroge pour savoir si tous
les gens de ce wagon vont en Amérique.  Si j'y vais.  « Oui. »  Elle s'excuse et me demande si elle peut
me demander ce que je vais y faire.  « Des conférences. »  « Littéraires ou scientifiques ?  —
Littéraires. »  Elle pousse un vrai cri de théâtre avec la main portée rapidement à la bouche.  « Ah !
dit-elle, comme c'est merveilleux. »  Et deux secondes après, les yeux baissés : « Moi aussi, je suis
dans la littérature.  — Ah ! » dis-je.  « Oui, je vais publier un livre de poèmes.  — Très bien, dis-je.
— Oui, j'ai obtenu une préface de Rosemonde Gérard.  Elle m'a fait un très beau sonnet.  — Bravo.  — Ah
! bien sûr, c'est mon premier livre.  Mais débuter dans la littérature avec une préface de Rosemonde
Gérard...  — Chez quel éditeur ? »  Elle me donne un nom que je ne connais pas.  Elle m'explique que ce
sont des vers réguliers « parce que je suis plutôt dans le genre classique.  Le moderne, moi, je ne sais
pas ce que vous en pensez... mais je n'aime pas ce que je ne comprends pas », etc., etc.  Elle descend à
Rouen et me propose de poster un télégramme que je veux envoyer à Paris parce que j'ai oublié l'adresse
de R. à New York.  Elle ne l'a pas posté puisque je n'ai pas reçu de réponse.

| une angoisse                | angst                  |
| propre                      | inherent, eigen        |
| prendre des contacts        | om contacten te leggen |
| un contact                  | contact                |
| fin et sympathique          | fijn en sympathiek     |
| turbulent                   | onstuimig              |
| assoupir                    | indommelen             |
| une bonne                   | kindermeid             |
| un petit bout de            | a little bit of a      |
| une longue fourrure de bête | een lange bontjas      |
| épaté                       | aplati, afgeplat       |
| cri de théâtre              | theatrale kreet        |
| un cri                      | kreet                  |
| un œil, des yeux            | oog, ogen              |
| une littérature             | literatuur             |
| un livre                    | boek                   |
| un poème                    | gedicht                |
| une préface                 | voorwoord              |
| un sonnet                   | klinkdicht, sonnet     |
| un éditeur                  | uitgever               |
| un vers                     | vers, dichtregel       |
| un genre                    | soort                  |
| un moderne                  | moderneg               |
| un télégramme               | telegram               |
| une adresse                 | adres                  |

Au wagon-restaurant, je retrouve R. et nous déjeunons en face du petit bout blond que n'arrive pas à
casser ses noix.  Au Havre, le petit bout de femme qui a l'air complètement perdu réclame mon
assistance.  En attendant le car nous parlons un peu.  Elle va à Philadelphie.  Le car est une ancienne
voiture cellulaire, sale, et poussiéreuse.  Le Havre, avec d'immenses chantiers de gravats.  L'air est
mou.  Quand nous arrivons devant l'Oregon je m'aperçois que c'est un cargo, un grand cargo, mais un
cargo.  Douane, change, commissariat avec la petite boîte de fiches qu'un flic consulte pendant qu'on
dit votre nom — et que je connais bien à cause de quelques sueurs fugitives qu'elle m'a données pendant
l'occupation.  Et puis à bord.

| un wagon-restaurant    | restauratiewagen                      |
| déjeuner               | lunchen                               |
| casser ses noix        | ennuyer ; s'ennuyer, se donner du mal |
| une noix               | noot                                  |
| une assistance         | hulp                                  |
| une voiture cellulaire | afgesloten wagen                      |
| un gravat              | schroot                               |
| un air                 | lucht                                 |
| mou                    | zacht                                 |
| un cargo               | vrachtschip                           |

La cabine à quatre avec salle de douches et W.-C. est devenue une cabine à cinq où il est impossible
d'éternuer sans renverser quelque chose.  On nous demande de passer à la salle à manger pour voir le
maître d'hôtel.  En réalité c'est pour assister à une scène de comédie.  Le maître d'hôtel ressemble aux
Français tels qu'on les voit dans les films américains et, de plus, se trouve affligé de tics qui lui
font distribuer de nombreuses œillades à droite et à gauche.  Il s'applique à composer des tables
harmonieuses et dispose à cet effet, comme les bonnes maîtresses de maison, d'un plan et du titre de
quelques-uns des passagers qui sont spécialement recommandés.  Naturellement il veut me mettre avec un
journaliste qui se trouve à bord.  Mais je refuse énergiquement et finalement je me retrouve avec R. et
le petit bout blond qui s'appelle, ô merveille, Jeanne Lorette.  C'est une petite Parisienne qui
travaille dans les parfums, qui pleurait ce matin parce qu'elle avait quitté sa sœur jumelle et que sa
sœur, c'est tout pour elle, mais elle va rejoindre à Philadelphie un Américain avec lequel elle doit se
marier.  R. est ravi par le naturel, la sagesse et la gentillesse de cette Lorette.  Moi aussi.  Nous
sommes un peu moins ravis par la cabine.  Le lit supplémentaire, au milieu, est occupé par un vieillard
de 70 ans.  La couchette au-dessus de la mienne est à un type d'âge moyen dont je présume qu'il est dans
les affaires.  Au-dessus de R. se trouve un vice-consul qui se rend à Shangaï et qui a la mine ouverte
et bruyante.  On s'installe et je décide de me mettre au travail.

| une cabine    | cabine      |
| éternuer      | niezen      |
| une salle     | zaal        |
| une scène     | scène       |
| une couchette | slaapplaats |
| un lit        | bed         |

Au dîner, je retrouve R., Lorette, la grande femme du compartiment (elle n'est pas si grande — mais
mince et élégante) et un couple de Mexicains « qui sont dans les affaires ».  Les deux femmes semblent
considérer notre Lorette avec un peu de méfiance.  Mais comme elle se contente d'être naturelle, c'est
elle qui garde le plus de classe.  Elle nous raconte que sa belle-mère qui ne la connaît pas lui envoie
les plus gentilles lettres et que les belles-mères semblent être en Amérique d'une qualité tout à fait
supérieure.  Son fiancé est très croyant, il ne boit ni ne fume.  Il lui a demandé de se confesser avant
de partir.  Le matin du départ (les jours d'avant, elle avait fait des démarches), elle s'est levée à
six heures pour aller à l'église mais elle était fermée et le train partait tôt.  Elle se confessera
donc là-bas et, dit-elle avec sa légère accentuation parisienne (pour le reste, elle articule très mal
et très vite et il faut pencher la tête pour saisir ce qu'elle dit) « J'aime mieux ça parce que celui de
là-bas ne comprendra pas bien ce que je lui dirai et comme ça il me donnera l'absolution. »  Nous lui
expliquons qu'on donne toujours l'absolution dans ces cas-là.  « Même pour les mortels. »  Mais oui, dit
R. convaincu.  Et nous lui signalons qu'il y a sans doute un aumônier sur le bateau.

Après dîner, R. et moi tombons d'accord sur le fait que cette charmante Lorette essaie de calmer son
appréhesion en présentant aux autres et par conséquent à elle-même une image réconfortante de la
situation — qui d'ailleurs est peut-être réconfortante, mais ce n'est pas la question.  En tout cas,
nous sommes encore d'accord pour souhaiter tout le bonheur qu'elle mérite à ce drôle de petit animal.

** pag. 19 bovenaan

** pag. 24

Dimanche.  On annonce que nous arriverons le soir.  La semaine s'est passée de façon vertigineuse.  Le
soir du mardi 21, notre table décide de fêter le printemps.  Alcool jusqu'à 4 heures du matin.  Le
lendemain aussi.  Quarante-huit heures d'euphorie agréable, où toutes les relations se précipitent.  Mme
D. est en pleine révolte contre son milieu.  L. m'avoue qu'elle va faire un mariage de raison.  Le
samedi nous avons quitté le Gulf-Stream et la température rafraîchit terriblement.  Le temps passe très
vite cependant et finalement je ne suis pas si pressé d'arriver.  J'ai terminé ma conférence.  Et le
reste du temps, je regarde la mer et je bavarde, surtout avec R., vraiment intelligent — et
naturellement Mme D. et L.

À 12 heures aujourd'hui, on aperçoit la terre.  Depuis le matin, des mouettes survolaient le bateau et
semblaient suspendues, immobiles, au-dessus des ponts.  Coney Island qui ressemble à la porte d'Orléans
nous apparaît d'abord.  « C'est Saint-Denis ou Gennevilliers », dit L.  C'est tout à fait vrai.  Dans le
froid, avec le vent gris et le ciel plat, tout cela est assez cafardeux.  Nous ancrons dans la baie
d'Hudson et ne débarquerons que demain matin.  Au loin, les gratte-ciel de Manhattan sur un fond de
brume.  J'ai le cœur tranquille et sec que je me sens devant les spectacles qui ne me touchent pas.

Lundi.  Coucher très tard la veille.  Lever très tôt.  Nous remontons le port de New York.  Spectacle
formidable malgré ou à cause de la brume.  L'ordre, la puissance, la force économique est là.  Le cœur
tremble devant tant d'admirable inhumanité.

Je ne débarque qu'à 11 heures après de longues formalités où seul de tous les passagers je suis traité
en suspect.  L'officier d'immigration finit par s'excuser de m'avoir tant retenu.  « J'y étais obligé
mais je ne puis vous dire pourquoi. »  Mystère, mais après cinq ans d'occupation !

Accueilli par C., E. et un envoyé du consulat.  C. inchangé.  E. non plus.  Mais dans toute cette foire,
les adieux avec L., Mme D. et R. sont rapides et froids.

Fatigué.  Ma grippe revient.  Et c'est les jambes flageolantes que je reçois le premier coup de New
York.  Au premier regard, hideuse ville inhumaine.  Mais je sais qu'on change d'avis.  Ce sont des
détails qui me frappent : que les ramasseurs d'ordures portent des gants, que la circulation est
disciplinée, sans intervention d'agents aux carrefours, etc., que personne n'a jamais de monnaie dans ce
pays et que tout le monde a l'air de sortir d'un film de série.  Le soir, traversant Broadway en taxi,
fatigué et fiévreux, je suis littéralement abasourdi par la foire lumineuse.  Je sors de cinq ans de
nuit et cette orgie de lumières voilentes me donne pour la première fois l'impression d'un nouveau
continent (une énorme enseigne de 15 m pour les Camel : un G.I. bouche grande ouverte laisse échapper
d'énormes bouffées de /vraie/ fumée.  Le tout est jaune et rouge).  Je me couche malade du cœur autant
que du corps, mais sachant parfaitement que j'aurai changé d'avis dans deux jours.
