# camus.org -*- coding: utf-8; mode: org -*- 

* Journaux de voyage https://www.theparisreview.org/blog/2023/03/14/camuss-new-york-diary-1946/

Dimanche.  On annonce que nous arriverons le soir.  La semaine s'est passée de façon vertigineuse.  Le
soir du mardi 21, notre table décide de fêter le printemps.  Alcool jusqu'à 4 heures du matin.  Le
lendemain aussi.  Quarante-huites heures d'euphorie agréable, où toutes les relations se précipitent.
Mme D. est en pleine révolte contre son milieu.  L. m'avoue qu'elle va faire un mariage de raison.  Le
samedi nous avons quitté le Gulf-Stream et la température rafraîchit terriblement.  Le temps passe très
vite cependant et finalement je ne suis pas si pressé d'arriver.  J'ai terminé ma conférence.  Et le
reste du temps, je regarde la mer et je bavarde, surtout avec R., vraiment intelligent — et
naturellement Mme D. et L.

À 12 heures aujourd'hui, on aperçoit la terre.  Depuis le matin, des mouettes survolaient le bateau et
semblaient suspendues, immobiles, au-dessus des ponts.  Coney Island qui ressemble à la porte d'Orléans
nous apparaît d'abord.  « C'est Saint-Denis ou Gennevilliers », dit L.  C'est tout à fait vrai.  Dans le
froid, avec le vent gris et le ciel plat, tout cela est assez cafardeux.  Nous ancrons dans la baie
d'Hudson et ne débarquerons que demain matin.  Au loin, les gratte-ciel de Manhattan sur un fond de
brume.  J'ai le cœur tranquille et sec que je me sens devant les spectacles qui ne me touchent pas.
