# camus.org -*- coding: utf-8; mode: org -*- 

* L'été

Mais toi tu es né pour un jour limpide...  (Hölderlin)

Cet essai date de 1939.  Le lecteur devra s'en souvenir pour juger de ce que pourrait être l'Oran
d'aujourd'hui.  Des protestations passionnées venues de cette belle ville m'assurent en effet qu'il a
été (ou sera) porté remède à toutes les imperfections.  Les beautés que cet essai exalte, au contraire,
ont été jalousement protégées.  Cité heureuse et réaliste, Oran désormais n'a plus besoin d'écrivains :
elle attend des touristes.  (1953)

** Le minotaure ou la halte d'Oran

Il n'y a plus des déserts.  Il n'y a plus d'îles.  Le besoin pourtant s'en fait sentir.  Pour comprendre
le monde, il faut parfois se détourner ; pour mieux servir les hommes, les tenir un moment à distance.
Mais où trouver la solitude nécessaire à la force, la longue respiration où l'esprit se rassemble et le
courage se mesure ?  Il reste les grandes villes.  Simplement, il y faut encore des conditions.

Les villes que l'Europe nous offre sont trop pleines des rumeurs du passé.  Une oreille exercée peut y
percevoir des bruits d'ailes, une palpitation d'âmes.  On y sent le vertige des siècles, des
révolutions, de la gloire.  On s'y souvient que l'Occident s'est forgé dans les clameurs.  Cela ne fait
pas assez de silence.

Paris est souvent un désert pour le cœur, mais à certaines heures, du haut du Père-Lachaise, souffle un
vent de révolution qui remplit soudain ce désert de drapeaux et de grandeurs vaincues.  Ainsi de
quelques villes espagnoles, de Florence ou de Prague.  Salzbourg serait paisible sans Mozart.  Mais, de
loin en loin, court sur la Salzach le grand cri orgueilleux de don Juan plongeant aux enfers.  Vienne
paraît plus silencieuse, c'est une jeune fille parmi les villes.  Les pierres n'y ont pas plus de trois
siècles et leur jeunesse ignore la mélancolie.  Mais Vienne est à un carrefour d'histoire.  Autour
d'elle retentissent des chocs d'empires.  Certains soirs où le ciel se couvre de sang, les cheavaux de
pierre, sur les monuments du Ring, semblent s'envoler.  Dans cet instant fugitif, où tout parle de
puissance et d'histoire, on peut distinctement entendre, sous la ruée des escadrons polonais, la chute
fracassante du royaume ottoman.  Cela non plus fait pas assez de silence.



* Journaux de voyage https://www.theparisreview.org/blog/2023/03/14/camuss-new-york-diary-1946/

                                               ÉTATS-UNIS
                                            Mars à mai 1946

Amérique.  Départ.  La légère angoisse propre à tout départ est passée.  Dans le train, je retrouve R.,
psychiatre qui va là-bas prendre des contacts.  Je sais qu'il sera dans ma cabine sur le bateau et ça ne
m'est pas désagréable parce que je le trouve fin et sympathique.  Dans mon compartiment, trois gosses
assez turbulents au départ, mais qui s'assoupiront, leur petite bonne, leur mère, grand et élégante
femme aux yeux clairs et un petit bout de femme blonde, qui pleure en face de moi.  Voyage sans
histoire, sauf une.  Je rends quelques services à la jeune femme blonde.  Avant Rouen, une sorte de
grande femme vêtue d'une longue fourrure de bête et aux traits épatés m'interroge pour savoir si tous
les gens de ce wagon vont en Amérique.  Si j'y vais.  « Oui. »  Elle s'excuse et me demande si elle peut
me demander ce que je vais y faire.  « Des conférences. »  « Littéraires ou scientifiques ?  —
Littéraires. »  Elle pousse un vrai cri de théâtre avec la main portée rapidement à la bouche.  « Ah !
dit-elle, comme c'est merveilleux. »  Et deux secondes après, les yeux baissés : « Moi aussi, je suis
dans la littérature.  — Ah ! » dis-je.  « Oui, je vais publier un livre de poèmes.  — Très bien, dis-je.
— Oui, j'ai obtenu une préface de Rosemonde Gérard.  Elle m'a fait un très beau sonnet.  — Bravo.  — Ah
! bien sûr, c'est mon premier livre.  Mais débuter dans la littérature avec une préface de Rosemonde
Gérard...  — Chez quel éditeur ? »  Elle me donne un nom que je ne connais pas.  Elle m'explique que ce
sont des vers réguliers « parce que je suis plutôt dans le genre classique.  Le moderne, moi, je ne sais
pas ce que vous en pensez... mais je n'aime pas ce que je ne comprends pas », etc., etc.  Elle descend à
Rouen et me propose de poster un télégramme que je veux envoyer à Paris parce que j'ai oublié l'adresse
de R. à New York.  Elle ne l'a pas posté puisque je n'ai pas reçu de réponse.

| une angoisse                | angst                  |
| propre                      | inherent, eigen        |
| prendre des contacts        | om contacten te leggen |
| un contact                  | contact                |
| fin et sympathique          | fijn en sympathiek     |
| turbulent                   | onstuimig              |
| assoupir                    | indommelen             |
| une bonne                   | kindermeid             |
| un petit bout de            | a little bit of a      |
| une longue fourrure de bête | een lange bontjas      |
| épaté                       | aplati, afgeplat       |
| cri de théâtre              | theatrale kreet        |
| un cri                      | kreet                  |
| un œil, des yeux            | oog, ogen              |
| une littérature             | literatuur             |
| un livre                    | boek                   |
| un poème                    | gedicht                |
| une préface                 | voorwoord              |
| un sonnet                   | klinkdicht, sonnet     |
| un éditeur                  | uitgever               |
| un vers                     | vers, dichtregel       |
| un genre                    | soort                  |
| un moderne                  | moderneg               |
| un télégramme               | telegram               |
| une adresse                 | adres                  |

Au wagon-restaurant, je retrouve R. et nous déjeunons en face du petit bout blond que n'arrive pas à
casser ses noix.  Au Havre, le petit bout de femme qui a l'air complètement perdu réclame mon
assistance.  En attendant le car nous parlons un peu.  Elle va à Philadelphie.  Le car est une ancienne
voiture cellulaire, sale, et poussiéreuse.  Le Havre, avec d'immenses chantiers de gravats.  L'air est
mou.  Quand nous arrivons devant l'Oregon je m'aperçois que c'est un cargo, un grand cargo, mais un
cargo.  Douane, change, commissariat avec la petite boîte de fiches qu'un flic consulte pendant qu'on
dit votre nom — et que je connais bien à cause de quelques sueurs fugitives qu'elle m'a données pendant
l'occupation.  Et puis à bord.

| un wagon-restaurant    | restauratiewagen                      |
| déjeuner               | lunchen                               |
| casser ses noix        | ennuyer ; s'ennuyer, se donner du mal |
| une noix               | noot                                  |
| une assistance         | hulp                                  |
| une voiture cellulaire | afgesloten wagen                      |
| un gravat              | schroot                               |
| un air                 | lucht                                 |
| mou                    | zacht                                 |
| un cargo               | vrachtschip                           |

La cabine à quatre avec salle de douches et W.-C. est devenue une cabine à cinq où il est impossible
d'éternuer sans renverser quelque chose.  On nous demande de passer à la salle à manger pour voir le
maître d'hôtel.  En réalité c'est pour assister à une scène de comédie.  Le maître d'hôtel ressemble aux
Français tels qu'on les voit dans les films américains et, de plus, se trouve affligé de tics qui lui
font distribuer de nombreuses œillades à droite et à gauche.  Il s'applique à composer des tables
harmonieuses et dispose à cet effet, comme les bonnes maîtresses de maison, d'un plan et du titre de
quelques-uns des passagers qui sont spécialement recommandés.  Naturellement il veut me mettre avec un
journaliste qui se trouve à bord.  Mais je refuse énergiquement et finalement je me retrouve avec R. et
le petit bout blond qui s'appelle, ô merveille, Jeanne Lorette.  C'est une petite Parisienne qui
travaille dans les parfums, qui pleurait ce matin parce qu'elle avait quitté sa sœur jumelle et que sa
sœur, c'est tout pour elle, mais elle va rejoindre à Philadelphie un Américain avec lequel elle doit se
marier.  R. est ravi par le naturel, la sagesse et la gentillesse de cette Lorette.  Moi aussi.  Nous
sommes un peu moins ravis par la cabine.  Le lit supplémentaire, au milieu, est occupé par un vieillard
de 70 ans.  La couchette au-dessus de la mienne est à un type d'âge moyen dont je présume qu'il est dans
les affaires.  Au-dessus de R. se trouve un vice-consul qui se rend à Shangaï et qui a la mine ouverte
et bruyante.  On s'installe et je décide de me mettre au travail.

| une cabine    | cabine      |
| éternuer      | niezen      |
| une salle     | zaal        |
| une scène     | scène       |
| une couchette | slaapplaats |
| un lit        | bed         |

Au dîner, je retrouve R., Lorette, la grande femme du compartiment (elle n'est pas si grande — mais
mince et élégante) et un couple de Mexicains « qui sont dans les affaires ».  Les deux femmes semblent
considérer notre Lorette avec un peu de méfiance.  Mais comme elle se contente d'être naturelle, c'est
elle qui garde le plus de classe.  Elle nous raconte que sa belle-mère qui ne la connaît pas lui envoie
les plus gentilles lettres et que les belles-mères semblent être en Amérique d'une qualité tout à fait
supérieure.  Son fiancé est très croyant, il ne boit ni ne fume.  Il lui a demandé de se confesser avant
de partir.  Le matin du départ (les jours d'avant, elle avait fait des démarches), elle s'est levée à
six heures pour aller à l'église mais elle était fermée et le train partait tôt.  Elle se confessera
donc là-bas et, dit-elle avec sa légère accentuation parisienne (pour le reste, elle articule très mal
et très vite et il faut pencher la tête pour saisir ce qu'elle dit) « J'aime mieux ça parce que celui de
là-bas ne comprendra pas bien ce que je lui dirai et comme ça il me donnera l'absolution. »  Nous lui
expliquons qu'on donne toujours l'absolution dans ces cas-là.  « Même pour les mortels. »  Mais oui, dit
R. convaincu.  Et nous lui signalons qu'il y a sans doute un aumônier sur le bateau.

Après dîner, R. et moi tombons d'accord sur le fait que cette charmante Lorette essaie de calmer son
appréhesion en présentant aux autres et par conséquent à elle-même une image réconfortante de la
situation — qui d'ailleurs est peut-être réconfortante, mais ce n'est pas la question.  En tout cas,
nous sommes encore d'accord pour souhaiter tout le bonheur qu'elle mérite à ce drôle de petit animal.

** pag. 19 bovenaan

** pag. 24

Dimanche.  On annonce que nous arriverons le soir.  La semaine s'est passée de façon vertigineuse.  Le
soir du mardi 21, notre table décide de fêter le printemps.  Alcool jusqu'à 4 heures du matin.  Le
lendemain aussi.  Quarante-huit heures d'euphorie agréable, où toutes les relations se précipitent.  Mme
D. est en pleine révolte contre son milieu.  L. m'avoue qu'elle va faire un mariage de raison.  Le
samedi nous avons quitté le Gulf-Stream et la température rafraîchit terriblement.  Le temps passe très
vite cependant et finalement je ne suis pas si pressé d'arriver.  J'ai terminé ma conférence.  Et le
reste du temps, je regarde la mer et je bavarde, surtout avec R., vraiment intelligent — et
naturellement Mme D. et L.

À 12 heures aujourd'hui, on aperçoit la terre.  Depuis le matin, des mouettes survolaient le bateau et
semblaient suspendues, immobiles, au-dessus des ponts.  Coney Island qui ressemble à la porte d'Orléans
nous apparaît d'abord.  « C'est Saint-Denis ou Gennevilliers », dit L.  C'est tout à fait vrai.  Dans le
froid, avec le vent gris et le ciel plat, tout cela est assez cafardeux.  Nous ancrons dans la baie
d'Hudson et ne débarquerons que demain matin.  Au loin, les gratte-ciel de Manhattan sur un fond de
brume.  J'ai le cœur tranquille et sec que je me sens devant les spectacles qui ne me touchent pas.

Lundi.  Coucher très tard la veille.  Lever très tôt.  Nous remontons le port de New York.  Spectacle
formidable malgré ou à cause de la brume.  L'ordre, la puissance, la force économique est là.  Le cœur
tremble devant tant d'admirable inhumanité.

Je ne débarque qu'à 11 heures après de longues formalités où seul de tous les passagers je suis traité
en suspect.  L'officier d'immigration finit par s'excuser de m'avoir tant retenu.  « J'y étais obligé
mais je ne puis vous dire pourquoi. »  Mystère, mais après cinq ans d'occupation !

Accueilli par C., E. et un envoyé du consulat.  C. inchangé.  E. non plus.  Mais dans toute cette foire,
les adieux avec L., Mme D. et R. sont rapides et froids.

Fatigué.  Ma grippe revient.  Et c'est les jambes flageolantes que je reçois le premier coup de New
York.  Au premier regard, hideuse ville inhumaine.  Mais je sais qu'on change d'avis.  Ce sont des
détails qui me frappent : que les ramasseurs d'ordures portent des gants, que la circulation est
disciplinée, sans intervention d'agents aux carrefours, etc., que personne n'a jamais de monnaie dans ce
pays et que tout le monde a l'air de sortir d'un film de série.  Le soir, traversant Broadway en taxi,
fatigué et fiévreux, je suis littéralement abasourdi par la foire lumineuse.  Je sors de cinq ans de
nuit et cette orgie de lumières voilentes me donne pour la première fois l'impression d'un nouveau
continent (une énorme enseigne de 15 m pour les Camel : un G.I. bouche grande ouverte laisse échapper
d'énormes bouffées de /vraie/ fumée.  Le tout est jaune et rouge).  Je me couche malade du cœur autant
que du corps, mais sachant parfaitement que j'aurai changé d'avis dans deux jours.
