# camus.org -*- coding: utf-8; mode: org -*- 

* Journaux de voyage https://www.theparisreview.org/blog/2023/03/14/camuss-new-york-diary-1946/

Dimanche.  On annonce que nous arriverons le soir.  La semaine s'est passée de façon vertigineuse.  Le
soir du mardi 21, notre table décide de fêter le printemps.  Alcool jusqu'à 4 heures du matin.  Le
lendemain aussi.  Quarante-huit heures d'euphorie agréable, où toutes les relations se précipitent.  Mme
D. est en pleine révolte contre son milieu.  L. m'avoue qu'elle va faire un mariage de raison.  Le
samedi nous avons quitté le Gulf-Stream et la température rafraîchit terriblement.  Le temps passe très
vite cependant et finalement je ne suis pas si pressé d'arriver.  J'ai terminé ma conférence.  Et le
reste du temps, je regarde la mer et je bavarde, surtout avec R., vraiment intelligent — et
naturellement Mme D. et L.

À 12 heures aujourd'hui, on aperçoit la terre.  Depuis le matin, des mouettes survolaient le bateau et
semblaient suspendues, immobiles, au-dessus des ponts.  Coney Island qui ressemble à la porte d'Orléans
nous apparaît d'abord.  « C'est Saint-Denis ou Gennevilliers », dit L.  C'est tout à fait vrai.  Dans le
froid, avec le vent gris et le ciel plat, tout cela est assez cafardeux.  Nous ancrons dans la baie
d'Hudson et ne débarquerons que demain matin.  Au loin, les gratte-ciel de Manhattan sur un fond de
brume.  J'ai le cœur tranquille et sec que je me sens devant les spectacles qui ne me touchent pas.

Lundi.  Coucher très tard la veille.  Lever très tôt.  Nous remontons le port de New York.  Spectacle
formidable malgré ou à cause de la brume.  L'ordre, la puissance, la force économique est là.  Le cœur
tremble devant tant d'admirable inhumanité.

Je ne débarque qu'à 11 heures après de longues formalités où seul de tous les passagers je suis traité
en suspect.  L'officier d'immigration finit par s'excuser de m'avoir tant retenu.  « J'y étais obligé
mais je ne puis vous dire pourquoi. »  Mystère, mais après cinq ans d'occupation !

Accueilli par C., E. et un envoyé du consulat.  C. inchangé.  E. non plus.  Mais dans toute cette foire,
les adieux avec L., Mme D. et R. sont rapides et froids.

Fatigué.  Ma grippe revient.  Et c'est les jambes flageolantes que je reçois le premier coup de New
York.  Au premier regard, hideuse ville inhumaine.  Mais je sais qu'on change d'avis.  Ce sont des
détails qui me frappent : que les ramasseurs d'ordures portent des gants, que la circulation est
disciplinée, sans intervention d'agents aux carrefours, etc., que personne n'a jamais de monnaie dans ce
pays et que tout le monde a l'air de sortir d'un film de série.  Le soir, traversant Broadway en taxi,
fatigué et fiévreux, je suis littéralement abasourdi par la foire lumineuse.  Je sors de cinq ans de
nuit et cette orgie de lumières voilentes me donne pour la première fois l'impression d'un nouveau
continent (une énorme enseigne de 15 m pour les Camel : un G.I. bouche grande ouverte laisse échapper
d'énormes bouffées de /vraie/ fumée.  Le tout est jaune et rouge).  Je me couche malade du cœur autant que
du corps, mais sachant parfaitement que j'aurai changé d'avis dans deux jours.
