# libretexts -*- coding: utf-8; mode: org -*- 

https://human.libretexts.org/Courses/Chabot_College/FRNC_1A%3A_Beginning_French/01%3A_Unite_1_-_Bonjour

* Unité 1 - Bonjour!

** Les mots apparentés

abondance, cercle, furieux, exactement, activités, différent, aventure, commun, animal, bicyclette,
guide, hôpital, correctement, musique, humain, observatoire, négocier, plat, université, solidifier

** Les faux amis

blessé, ancien, attendre, monnaie, déception, envie, jolie, journée, librarie, crayon, rester

** Contexte

Je l'aime   I love her
Je j'aime bien   I like her

** Comment se saluer

*** Les saluations

Bonjour, Salut, Bonsoir

*** Questions

Comment ça va ?
Ça va ?

Comment va-tu ?
Comment allez-vous ?

*** Réponses

Ça va.
Ça va (très) bien.
Ça va comme-ci, comme-ça.
Pas mal.
Ça va (très) mal.
Non, ça ne va pas.

Je vais (très) bien.
Je vais (très) mal.

*** Les adieux

Au revoir.
À bientôt.
À demain.
À plus tard (À plus).
À ce soir.
À tout à l'heure.
À tout de suite !
Bonne journèe.
Bonne soirée.
Ciao.
Salut.
À la prochaine.
Adieu.

*** Formules de politesse

Merci.
Merci beaucoup.
De rien.
Je vous en prie.
Je t'en prie.
Pardon.
Excusez-moi.
Excuse-moi.
S'il vous plaît.
S'il te plaît.

*** Les étiquettes

Monsieur.
Madame.
Mademoiselle.
